services:
  yehiaDB:
    image: mysql:latest
    container_name: yehiaDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "yehia"
    volumes:
      - ../dbFiles:/docker-entrypoint-initdb.d
    restart: always
